# version: '3.8'

services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: wp-php
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
    networks:
      - wpsite

  db:
    image: mariadb:10.5
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wpsite

  nginx:
    image: nginx:latest
    container_name: wp-nginx
    restart: always
    ports:
      - "8000:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./wordpress:/var/www/html:ro
      - ./certs:/etc/ssl/certs:ro

    depends_on:
      - wordpress
    networks:
      - wpsite
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    networks:
      - wpsite

volumes:
  db_data:

networks:
  wpsite:
